### ISSUE TITLE
Fill in the TODO TODO TODO TODO on the README.

### ISSUE THREAD

**Issue by ajbogh** [ghostbar/RTSP-Streaming.js#1]
The How to Use section is incomplete. Please fill in that section with an example of how to use this software.

**Comment by ghostbar** [comment]
You need ffmpeg installed;

Run `node server/server.js` it will fire the web client on port 8081.

Sources at listed from line 141 on `server/server.js` and those are streamed to websockets. on channels 001, 002, 003, 004.
